import calendar
import math
from ast import literal_eval
from datetime import date, timedelta
from decimal import Decimal

from odoo import _, api, fields, models
from odoo.addons.cryptosync.utils.cryptosync import FEE_PATERN
from odoo.exceptions import UserError


class CryptoTransactionLine(models.Model):
    _name = "crypto.transaction.line"
    _description = "Cryptocurrency Transaction Detail"
    _order = "date,name,id"

    transaction_id = fields.Many2one(
        "crypto.transaction", string="Master Transaction", readonly=True, ondelete="cascade"
    )

    name = fields.Char("Label", readonly=True)
    date = fields.Datetime("Date", readonly=True)
    description = fields.Char("Description", readonly=True)
    address = fields.Char("Address", readonly=True)
    currency_id = fields.Many2one("res.currency", string="Currency", readonly=True)
    value = fields.Monetary("Value", currency_field="currency_id", readonly=True)
    value_str = fields.Char("Value (raw)", readonly=True)

    state = fields.Selection(
        [("ready", "Ready"), ("done", "Done"), ("ignored", "Ignored")],
        string="State",
        default="ready",
        readonly=True,
    )
    journal_id = fields.Many2one("account.journal", string="Journal", compute="_compute_journal_id", store=True)
    account_id = fields.Many2one("account.account", string="Account", compute="_compute_account_id", store=True)
    partner_id = fields.Many2one("res.partner", string="Partner", compute="_compute_partner_id", store=True)
    statement_line_ids = fields.One2many(
        "account.bank.statement.line",
        "crypto_transaction_id",
        string="Statement Lines",
        readonly=True,
    )
    wallet_id = fields.Many2one(
        "res.partner.bank",
        string="Wallet",
        related="transaction_id.wallet_id",
        store=True,
    )

    @api.depends("wallet_id", "currency_id")
    def _compute_journal_id(self):
        journals = {
            (j.bank_account_id.id, j.currency_id.id): j
            for j in self.env["account.journal"].search(
                [
                    ("type", "=", "bank"),
                    ("bank_statements_source", "=", "crypto"),
                ]
            )
        }
        for tx in self:
            # Statements are generated by wallet and by currency
            jkey = tx.wallet_id.id, tx.currency_id.id
            tx.journal_id = journals.get(jkey)

    def _compute_account_id(self):
        self.account_id = False
        rules = self.env["crypto.account.rule"].search([])
        for rule in rules:
            results = self.search(literal_eval(rule.domain))
            for tx in self:
                if not tx.account_id and tx.wallet_id.crypto_provider_id == rule.provider_id and tx in results:
                    # not override account + force same provider
                    tx.account_id = rule.account_id

    @api.depends("address", "name")
    def _compute_partner_id(self):
        self.partner_id = False
        for tx in self:
            address = tx.address
            if not address and FEE_PATERN.match(tx.name):
                # if many addresses, get the one of the biggest amount
                tx = tx.transaction_id.output_ids.filtered("address").sorted("value", True)
                if not tx:
                    continue
                address = tx[0].address
            if not address:
                continue
            bank_account = self.env["res.partner.bank"].search([("acc_number", "=ilike", address)], limit=1)
            if bank_account:
                tx.partner_id = bank_account.partner_id

    @api.model_create_multi
    def create(self, vals_list):
        if self.env.context.get("fix_crypto_units"):
            currencies = {
                cur.id: cur.crypto_unit or 1
                for cur in self.env["res.currency"].with_context(active_test=False).search([])
            }
            for vals in vals_list:
                currency_id = vals.get("currency_id")
                if not currency_id:
                    continue
                if "value" in vals:
                    vals["value"] = float(Decimal(str(vals["value"])) / Decimal(currencies.get(currency_id, 1)))
                if "value_str" in vals:
                    vals["value_str"] = Decimal(vals["value_str"]) / Decimal(currencies.get(currency_id, 1))

        res = super().create(vals_list)
        for vals in vals_list:
            if "state" in vals:
                self.transaction_id._recompute_state()
        return res

    def write(self, vals):
        res = super().write(vals)
        if "state" in vals:
            self.transaction_id._recompute_state()
        return res

    def generate_statements(self, group_by=None):
        self = self.filtered(lambda x: x.state == "ready")
        self._compute_journal_id()

        statements = self._generate_statement_lines(group_by)
        statements = self._split_statements(statements)
        statements = self._clean_statements(statements, group_by)

        stmts = self.env["account.bank.statement"].create(statements)
        # stmts.with_context(no_error=True).recompute_balance()

        return {
            "type": "ir.actions.act_window",
            "name": _("Generated Statements"),
            "res_model": "account.bank.statement",
            "domain": [("id", "in", stmts.ids)],
            "view_mode": "list,form",
        }

    def _generate_statement_lines(self, group_by=None):
        statements = {}
        for tx in self:
            if not tx.journal_id:
                raise UserError(
                    _("No journal found for account {acc} and currency {ccy}.").format(
                        acc=tx.transaction_id.wallet_id.acc_number,
                        ccy=tx.currency_id.name,
                    )
                )

            if not group_by:
                period = None
            elif group_by == "week":
                period = tx.date.isocalendar()[:2]
            elif group_by == "month":
                period = tx.date.month, tx.date.year
            elif group_by == "year":
                period = tx.date.year

            skey = tx.journal_id.id, period

            if skey not in statements:
                # Init statement
                statements[skey] = {
                    "_period": period,
                    "name": "{} - {}".format(
                        tx.journal_id.bank_account_id.bank_name or tx.journal_id.bank_account_id.acc_number,
                        tx.journal_id.currency_id.name,
                    ),
                    "journal_id": tx.journal_id,
                    "line_ids": [],
                    "balance_start": 0,
                    "balance_end_real": 0,
                }

            statement = statements[skey]
            line = {
                "date": tx.date,
                "account_number": tx.address,
                "payment_ref": tx.name,
                "narration": tx.description,
                "amount": tx.value,
                "amount_currency_str": tx.value_str,
                "crypto_transaction_id": tx.id,
            }

            if tx.partner_id:
                line["partner_id"] = tx.partner_id.id

            statement["line_ids"].append((0, 0, line))

        self.state = "done"
        return list(statements.values())

    def _split_statements(self, statements):
        LINES_LIMIT = int(self.env["ir.config_parameter"].sudo().get_param("crypto_sync.statement_lines_limit", 0))

        if not LINES_LIMIT:
            return statements

        new_statements = []

        for statement in statements:
            statement["_total"] = math.ceil(len(statement["line_ids"]) / LINES_LIMIT)
            statement["line_ids"] = sorted(statement["line_ids"], key=lambda x: x[2]["date"])

            for i in range(statement["_total"]):
                new_statement = statement.copy()
                new_statement["_part"] = i + 1
                new_statement["line_ids"] = statement["line_ids"][i * LINES_LIMIT : (i + 1) * LINES_LIMIT]
                new_statements.append(new_statement)

        return new_statements

    def _clean_statements(self, statements, group_by=None):
        for statement in statements:
            first = min([line[2] for line in statement["line_ids"]], key=lambda l: l["date"])
            last = max([line[2] for line in statement["line_ids"]], key=lambda l: l["date"])
            if not group_by:
                date_from = first["date"].date()
                date_to = last["date"].date()
                if date_from == date_to:
                    statement["name"] += " - {}".format(date_from)
                else:
                    statement["name"] += " - {}-{}".format(date_from, date_to)
                statement["date"] = date_to
            elif group_by == "week":
                statement["name"] += " - {}, {} {}".format(statement["_period"][0], _("Week"), statement["_period"][1])
                statement["date"] = date.fromisocalendar(*statement["_period"], 7)
            elif group_by == "month":
                statement["name"] += " - {} {}".format(
                    calendar.month_name[statement["_period"][0]],
                    statement["_period"][1],
                )
                statement["date"] = date(
                    statement["_period"][1] + (1 if statement["_period"][0] == 12 else 0),
                    statement["_period"][0] % 12 + 1,
                    1,
                ) - timedelta(days=1)
            elif group_by == "year":
                statement["name"] += " - {}".format(statement["_period"])
                statement["date"] = date(statement["_period"], 1, 1) - timedelta(days=1)

            part, total = statement.get("_part", 1), statement.get("_total", 1)
            if total != 1:
                statement["name"] += " ({}/{})".format(part, total)

            for key in list(statement.keys()):
                if key.startswith("_"):
                    statement.pop(key)

            statement["journal_id"] = statement["journal_id"].id
        return statements

    def get_fiat_value(self) -> float:
        self.ensure_one()
        return self.currency_id._convert(self.value, self.env.company.currency_id, self.env.company, self.date)

    def action_open_parent(self):
        self.ensure_one()
        return {
            "type": "ir.actions.act_window",
            "res_model": "crypto.transaction",
            "view_type": "form",
            "view_mode": "form",
            "res_id": self.transaction_id.id,
        }
